config/routes.rb
Hrhome::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  match 'home/analytics' => 'home#analytics'
  match 'home/performance' => 'home#performance'
  match 'home/dictionary' => 'home#dictionary'
  match 'home/database' => 'home#database'

  resources :home

  match 'chandelier/graphs' => 'chandelier#graphs'
  match 'chandelier/fte' => 'chandelier#fte'
  match 'chandelier/employees' => 'chandelier#employees'
  match 'chandelier/salary' => 'chandelier#salary'

  resources :chandelier

  resources :competencies

  resources :positions do
    member do
      get 'edit_job_description'
      get 'edit_hr_profile'
      get 'edit_competency_profile'
      get 'steal'
    end
  end

  resources :offices

  root :to => 'home#index'

end

app/models/position.rb
class Position < ActiveRecord::Base
  acts_as_xlsx

  before_create :age

  attr_accessible :job_title, :office, :valid_from, :job_grade, :reports_to, :line_manages,
                  :overall_purpose, :scope, :specific_work_env, :conceptual, :implementation,
                  :support, :fte, :unique_position, :permanent, :department, :name,
                  :birth_date, :gender, :nationality, :res_status, :start_date, :type_contract,
                  :next_performance_talk, :age, :competencies_attributes,
                  :attitude1, :attitude2, :attitude3, :attitude4, :attitude5, :favorite_color
  has_many :tweets
  has_many :competencies
  accepts_nested_attributes_for :competencies, allow_destroy: true

  def position_status
    if name.present?
      "Filled"
    else
      "Vacant"
    end
  end

  def permanent_outcome
    if permanent == 1
      "permanent"
    else
      "temporarily"
    end
  end

  def name_of_office
    if office == 1
      "International"
    elsif office == 2
      "Netherlands"
    elsif office == 3
      "Germany"
    elsif office == 4
      "Mediterranean"
    elsif office == 5
      "United Kingdom"
    else
      "Unidentified"
    end
  end

  def job_description_title
    'GREENPEACE ' + name_of_office.to_s + ' ' + job_title.to_s + ' Job Description'
  end

  def attitude1_excel
    unless attitude1 == ''
      '- ' + attitude1.to_s
    end
  end

  def attitude2_excel
    unless attitude2 == ''
      '- ' + attitude2.to_s
    end
  end

  def attitude3_excel
    unless attitude3 == ''
      '- ' + attitude3.to_s
    end
  end

  def attitude4_excel
    unless attitude4 == ''
      '- ' + attitude4.to_s
    end
  end

  def attitude5_excel
    unless attitude5 == ''
      '- ' + attitude5.to_s
    end
  end

  def age
    if birth_date.nil?
      "0"
    else
      now = Time.now.utc.to_date
      now.year - birth_date.year - ((now.month > birth_date.month || (now.month == birth_date.month && now.day >= birth_date.day)) ? 0 : 1)
    end
  end

end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @positions }
    end
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
    @position = Position.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @position }
      format.xlsx
      format.xls
    end
  end

  # GET /positions/new
  # GET /positions/new.json
  def new
    @position = Position.new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @position }
    end
  end

  # GET /positions/1/edit
  def edit
    @position = Position.find(params[:id])
    @tweet = Tweet.new
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(params[:position])
    @tweet = Tweet.new(params[:tweet])

    respond_to do |format|
      if @position.save
        @tweet.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render json: @position, status: :created, location: @position }
      else
        format.html { render action: "new" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /positions/1
  # PUT /positions/1.json
  def update
    @position = Position.new
    @tweet = Tweet.new(params[:tweet])

    respond_to do |format|
      if params[:steal_button]
        @position.update_attributes(params[:position])
        @tweet.save
        format.html { redirect_to home_index_path, notice: 'Yay, position was successfully stolen.' }
        format.json { head :no_content }
      elsif @position.update_attributes(params[:position])
        @tweet.save
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position = Position.find(params[:id])
    @position.destroy

    respond_to do |format|
      format.html { redirect_to positions_url }
      format.json { head :no_content }
    end
  end

  def edit_job_description
    @position = Position.find(params[:id])
    @tweet = Tweet.new
  end

  def edit_hr_profile
    @position = Position.find(params[:id])
    @tweet = Tweet.new
  end

  def edit_competency_profile
    @position = Position.find(params[:id])
    @tweet = Tweet.new
    1.times { @position.competencies.build }

    respond_to do |format|
      format.html # edit_competency_profile.html.erb
      format.json { render json: @position }
    end
  end

  def steal
    @position = Position.find(params[:id])
    @tweet = Tweet.new
  end
end

app/helpers/positions_helper.rb
module PositionsHelper

  def tweet_created_by
    "was created by #{current_user.user_name}"
  end

  def tweet_updated_by
    "was updated by #{current_user.user_name}"
  end

  def jd_tweet_updated_by
    "was updated (job description) by #{current_user.user_name}"
  end

  def hrp_tweet_updated_by
    "was updated (hr profile) by #{current_user.user_name}"
  end

  def cp_tweet_updated_by
    "was updated (competency profile) by #{current_user.user_name}"
  end
end

app/views/positions/_competency_fields.html.erb
<fieldset>
  <% if current_user.language == 1 %>
    <td><%= f.select(:competency_name,  Competency.order(:id).where("competency_name like ?", "%#{params[:term]}%").map(&:competency_name).uniq) %></td>
  <% elsif current_user.language == 2 %>
    <td><%= f.select(:competency_name,  Competency.order(:id).where("competency_name like ?", "%#{params[:term]}%").map(&:spanish).uniq) %></td>
  <% elsif current_user.language == 2 %>
    <td><%= f.select(:competency_name,  Competency.order(:id).where("competency_name like ?", "%#{params[:term]}%").map(&:french).uniq) %></td>
  <% else %>
    <td><%= f.select(:competency_name,  Competency.order(:id).where("competency_name like ?", "%#{params[:term]}%").map(&:competency_name).uniq) %></td>
  <% end %>

  <td><%= f.select(:competency_value, [['1'],['2'],['3'],['4']], { :prompt => "0"}, :id => "select_field") %></td>
  <td><%= f.select(:competency_cpv, [['1'],['2'],['3'],['4']], { :prompt => "0"}, :id => "select_field") %></td>
  <td><%= f.hidden_field :_destroy %>
      <%= link_to "remove", '#', class: "remove_fields" %></td>
</fieldset>

app/views/positions/_edit_form.html.erb
<%= form_for(@position) do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<ul id="editposition" class="nav nav-tabs">
  <li class="active"><a href="#general" data-toggle="tab">General</a></li>
  <li><a href="#details" data-toggle="tab">Details</a></li>
  <li><a href="#activity" data-toggle="tab">Activity</a></li>
</ul>

<div id="editposition" class="tab-content">
  <div class="tab-pane fade in active" id="general">
    <p><%= render 'positions/forms/position/new_general', :f => f %></p>
  </div>

  <div class="tab-pane fade" id="details">
    <p><%= render 'positions/forms/position/new_details', :f => f %></p>
  </div>

  <div class="tab-pane fade" id="activity">
    <p>
      <%= fields_for(@tweet) do |fa| %>
        <div class="field">
          <%= fa.label :body, "Activity" %><hr />
          <%= fa.text_area :body, :placeholder => "Add here your activity notes, for example: Need to create a job description." %>
        </div>

        <div class="hidden">
          <%= fa.label :tweet_office %><br />
          <%= fa.number_field :tweet_office, :value => current_user.user_office %>
        </div>

        <div class="hidden">
          <%= fa.label :tweet_position %><br />
          <%= fa.text_field :tweet_position, :value => @position.job_title %>
        </div>

        <div class="hidden">
          <%= fa.label :tweet_name %><br />
          <%= fa.text_field :tweet_name, :value => tweet_updated_by  %>
        </div>

      <% end %>

      <div class="actions">
        <%= f.submit %>
      </div>
    </p>
  </div>
</div>

<% end %>

app/views/positions/_form.html.erb
<%= form_for(@position) do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :job_title %><br />
    <%= f.text_field :job_title %>
  </div>

  <div class="field">
    <%= f.label :office %><br />
    <%= f.number_field :office %>
  </div>

  <%= fields_for(@tweet) do |fa| %>
    <div class="field">
      <%= fa.label :body %><br />
      <%= fa.text_area :body, :value => "position created by person X" %>
    </div>
  <% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/positions/_new_form.html.erb
<%= form_for(@position) do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<ul id="position" class="nav nav-tabs">
  <li class="active"><a href="#general" data-toggle="tab">General</a></li>
  <li><a href="#details" data-toggle="tab">Details</a></li>
  <li><a href="#activity" data-toggle="tab">Activity</a></li>
</ul>

<div id="position" class="tab-content">
  <div class="tab-pane fade in active" id="general">
    <p><%= render 'positions/forms/position/new_general', :f => f %></p>
  </div>

  <div class="tab-pane fade" id="details">
    <p><%= render 'positions/forms/position/new_details', :f => f %></p>
  </div>

  <div class="tab-pane fade" id="activity">
    <p>
      <%= fields_for(@tweet) do |fa| %>
        <div class="field">
          <%= fa.label :body, "Activity" %><hr />
          <%= fa.text_area :body, :placeholder => "Add here your activity notes, for example: Need to create a job description." %>
        </div>

        <div class="hidden">
          <%= fa.label :tweet_office %><br />
          <%= fa.number_field :tweet_office, :value => current_user.user_office %>
        </div>

        <div class="hidden">
          <%= fa.label :tweet_position %><br />
          <%= fa.text_field :tweet_position, :id => "tweet_title" %>
        </div>

        <div class="hidden">
          <%= fa.label :tweet_name %><br />
          <%= fa.text_field :tweet_name, :value => tweet_created_by  %>
        </div>

      <% end %>

      <div class="actions">
        <%= f.submit %>
      </div>
    </p>
  </div>
</div>

<% end %>

app/views/positions/_steal_form.html.erb
<%= form_for(@position) do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<ul id="editposition" class="nav nav-tabs">
  <li class="active"><a href="#general" data-toggle="tab">General</a></li>
  <li><a href="#details" data-toggle="tab">Details</a></li>
  <li><a href="#activity" data-toggle="tab">Activity</a></li>
</ul>

<div id="editposition" class="tab-content">
  <div class="tab-pane fade in active" id="general">
    <p><%= render 'positions/forms/position/new_general', :f => f %></p>
  </div>

  <div class="tab-pane fade" id="details">
    <p><%= render 'positions/forms/position/new_details', :f => f %></p>
  </div>

  <div class="tab-pane fade" id="activity">
    <p>
      <%= fields_for(@tweet) do |fa| %>
        <div class="field">
          <%= fa.label :body, "Activity" %><hr />
          <%= fa.text_area :body, :placeholder => "Add here your activity notes, for example: Need to create a job description." %>
        </div>

        <div class="hidden">
          <%= fa.label :tweet_office %><br />
          <%= fa.number_field :tweet_office, :value => current_user.user_office %>
        </div>

        <div class="hidden">
          <%= fa.label :tweet_position %><br />
          <%= fa.text_field :tweet_position, :value => @position.job_title %>
        </div>

        <div class="hidden">
          <%= fa.label :tweet_name %><br />
          <%= fa.text_field :tweet_name, :value => tweet_updated_by  %>
        </div>

      <% end %>

      <div class="actions">
        <%= f.submit "Steal JD", :name => "steal_button" %>
      </div>
    </p>
  </div>
</div>

<% end %>

app/views/positions/edit.html.erb
<h1>Editing <%= @position.job_title %></h1>

<%= render 'edit_form' %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/edit_competency_profile.html.erb
<h1>Edit competencies</h1>

<%= render 'positions/forms/competency_profile/edit_competency_profile' %>

app/views/positions/edit_hr_profile.html.erb
<h1>Edit HR profile of <%= @position.job_title %></h1>

<%= render 'positions/forms/hr_profile/edit_hr_profile' %>

app/views/positions/edit_job_description.html.erb
<h1>Edit <%= @position.job_title %></h1>

<%= render 'positions/forms/job_description/edit_job_description' %>

app/views/positions/index.html.erb
<h1>Listing positions</h1>

<table>
  <tr>
    <th>Job title</th>
    <th>Office</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @positions.each do |position| %>
  <tr>
    <td><%= position.job_title %></td>
    <td><%= position.office %></td>
    <td><%= link_to 'Show', position %></td>
    <td><%= link_to 'Edit', edit_position_path(position) %></td>
    <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>Yay! New position</h1>

<%= render 'new_form' %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<div id="showCarousel" class="carousel slide" data-interval="false">
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
      <%= render 'positions/show/job_description' %>
    </div>
    <div class="item">
      <%= render 'positions/show/competency_profile' %>
    </div>
    <div class="item">
      <%= render 'positions/show/hr_profile' %>
    </div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#showCarousel" data-slide="prev" id="left_button">&lsaquo;</a>
  <a class="carousel-control right" href="#showCarousel" data-slide="next" id="right_button">&rsaquo;</a>
</div>

app/views/positions/show.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">

  <Worksheet ss:Name="Guidelines">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">What is a Profiency Level</Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String"></Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">The proficiency scale describes an individual’s level of expertise in a particular competency.</Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">It describes the degree to which an employee possesses a competency.</Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">Each level in the proficiency scale has a detailed description to help identify an employee’s level of proficiency.</Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">All 3 types of competencies are segregated into 4 proficiency levels:</Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">- Beginner</Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">- Basic</Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">- Intermediate</Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">- Advanced</Data></Cell>
      </Row>
    </Table>
  </Worksheet>

  <Worksheet ss:Name="<%= @position.name %>">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Competency</Data></Cell>
        <Cell><Data ss:Type="String">Reqested Profiency level</Data></Cell>
        <Cell><Data ss:Type="String">Competency value</Data></Cell>
        <Cell><Data ss:Type="String">Personal value</Data></Cell>
      </Row>
    <% for competency in @position.competencies %>
      <Row>
        <Cell><Data ss:Type="String"><%=h competency.competency_name %></Data></Cell>
        <Cell><Data ss:Type="Number"><%=h competency.competency_cpv %></Data></Cell>
        <Cell><Data ss:Type="Number"><%=h competency.competency_value %></Data></Cell>
        <Cell><Data ss:Type="Number"></Data>0</Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>

</Workbook>

app/views/positions/steal.html.erb
<h1>Copying <%= @position.job_title %></h1>

<%= render 'steal_form' %>