config/routes.rb
Hrhome::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  match 'home/analytics' => 'home#analytics'
  match 'home/performance' => 'home#performance'
  match 'home/dictionary' => 'home#dictionary'
  match 'home/database' => 'home#database'

  resources :home

  match 'chandelier/graphs' => 'chandelier#graphs'
  match 'chandelier/fte' => 'chandelier#fte'
  match 'chandelier/employees' => 'chandelier#employees'
  match 'chandelier/salary' => 'chandelier#salary'

  resources :chandelier

  resources :competencies

  resources :positions do
    member do
      get 'edit_job_description'
      get 'edit_hr_profile'
      get 'edit_competency_profile'
      get 'steal'
    end
  end

  resources :offices

  root :to => 'home#index'

end

app/controllers/chandelier_controller.rb
class ChandelierController < ApplicationController
  def index

  end

  def graphs

  end

  def fte

  end

  def employees

  end

  def salary

  end
end

app/helpers/chandelier_helper.rb
module ChandelierHelper
end

app/views/chandelier/_employees_pie_chart.html.erb
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = google.visualization.arrayToDataTable([
      ['Office', 'Size (employees)'],
      ['International', <%= Position.count(:job_title, :conditions => { :office => "1"}) %>],
      ['Netherlands', <%= Position.count(:job_title, :conditions => { :office => "2"}) %>],
      ['Germany', <%= Position.count(:job_title, :conditions => { :office => "3"}) %>],
      ['Mediterranean', <%= Position.count(:job_title, :conditions => { :office => "4"}) %>],
      ['United Kingdom', <%= Position.count(:job_title, :conditions => { :office => "5"}) %>]
    ]);

    var options = {
      title: 'Number of employees per office'
    };

    var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
    chart.draw(data, options);
  }
</script>


<div id="chart_div"></div>

app/views/chandelier/_fte_pie_chart.html.erb
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = google.visualization.arrayToDataTable([
      ['Office', 'Size (fte)'],
      ['International', <%= Position.sum(:fte, :conditions => { :office => "1"}) %>],
      ['Netherlands', <%= Position.sum(:fte, :conditions => { :office => "2"}) %>],
      ['Germany', <%= Position.sum(:fte, :conditions => { :office => "3"}) %>],
      ['Mediterranean', <%= Position.sum(:fte, :conditions => { :office => "4"}) %>],
      ['United Kingdom', <%= Position.sum(:fte, :conditions => { :office => "5"}) %>]
    ]);

    var options = {
      title: 'Number of FTE per office'
    };

    var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
    chart.draw(data, options);
  }
</script>


<div id="chart_div"></div>

app/views/chandelier/_menu.html.erb
<div class= "graphs">
    <p><em>Graphs</em></p>
    <%= link_to 'fte', chandelier_fte_path, :class => 'btn' %><br/>
    <%= link_to 'employees', chandelier_employees_path, :class => 'btn' %><br/>
    <%= link_to 'salary', chandelier_salary_path, :class => 'btn' %><br/>
</div>

app/views/chandelier/employees.html.erb
<h2>Graphs</h2>
<hr />
<div class="row-fluid">
  <div class="span2">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />
    <p><i>Livescreen Toolbox</i></p>
    <ul id="menu">
    <li><%= link_to 'Dictionary', competencies_path %></li>
    <li><%= link_to 'Visualisation', chandelier_graphs_path %></li>
    </ul>
  </div>

  <div class="span8">
    <h4>Employees</h4>
      <%= render 'employees_pie_chart' %>
  </div>

  <div class="span2">
    <%= render 'menu' %>
  </div>
</div>

app/views/chandelier/fte.html.erb
<h2>Graphs</h2>
<hr />
<div class="row-fluid">
  <div class="span2">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />
    <p><i>Livescreen Toolbox</i></p>
    <ul id="menu">
    <li><%= link_to 'Dictionary', competencies_path %></li>
    <li><%= link_to 'Visualisation', chandelier_graphs_path %></li>
    </ul>
  </div>

  <div class="span8">
    <h4>FTE</h4>
      <%= render 'fte_pie_chart' %>
  </div>

  <div class="span2">
    <%= render 'menu' %>
  </div>
</div>

app/views/chandelier/graphs.html.erb
<h2>Graphs</h2>
<hr />
<div class="row-fluid">
  <div class="span2">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />
    <p><i>Livescreen Toolbox</i></p>
    <ul id="menu">
    <li><%= link_to 'Dictionary', competencies_path %></li>
    <li><%= link_to 'Visualisation', chandelier_graphs_path %></li>
    </ul>
    <br/>
    <%= link_to 'Back', chandelier_index_path, :class => 'btn' %>
    <br/>
  </div>

  <div class="span8">
    <h4>Training tool</h4>
    <p>In the future it might be useful to build in a training request (based upon a competency). Then the use could file such request in their operational part and would be displayed on the livescreen. This could help GPI centralising their trainings/e-workshops to reduce their carbon footprint and be updated about the areas need for skills is needed.</p>
  </div>

  <div class="span2">
    <%= render 'menu' %>
  </div>
</div>

app/views/chandelier/index.html.erb
<h2>Dashboard</h2>
<hr />
<div class="row-fluid">
  <div class="span2">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />
    <p><i>Livescreen Toolbox</i></p>
    <ul id="menu">
    <li><%= link_to 'Dictionary', competencies_path %></li>
    <li><%= link_to 'Training', chandelier_graphs_path %></li>
    </ul>
    <br/>
    <br/>
    <%= link_to 'Operational screen', home_index_path, :class => 'btn' %>
  </div>

  <div class="span8">
    <h4>Livescreen</h4>
    <p>This page is the dashboard of GPI (also called livescreen). Next to the operational page of GPI (and other NROs) exists this page which allows GPI to manage several HR processes.</p>

    <h4>The Dictionary</h4>
    <p>You will be able to manage the competency dictionary from here. If you go to the dictionary tool you will be able to create competencies which will be added to the selection list for competencies on the operational level. In this way GPI will be in control of the list of competencies which can be used.</p>

    <h4>Visualisation (graphs)</h4>
    <p>By using google graphs it would be possible to display some neat graphs about the current HR state of the offices. To give you a little taste please click on the graph links on the right side.</p>
    <p>For the future this would be useful for generating reports aswell as having a table overview of the current HR state of each office. This could help in de decision making process and simplifies reporting process for NROs and GPI.</p>

    <h5>Future development</h5>
    <p>In the future this will be a highly interactive screen in order to assist HR processes globally.</p>
    <p>Future functions of the dashboard could include:
    <ul>
      <li>Salary overview of all offices</li>
      <li>Announcement function(s) and other communication tools</li>
      <li>Requests overview and other interaction tools</li>
      <li>Reporting functions exportable to pdf and excel</li>
    </ul>
    </p>
  </div>

  <div class="span2">
    <%= render 'menu' %>
  </div>
</div>

app/views/chandelier/salary.html.erb
<h2>Graphs</h2>
<hr />
<div class="row-fluid">
  <div class="span2">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />
    <p><i>Livescreen Toolbox</i></p>
    <ul id="menu">
    <li><%= link_to 'Dictionary', competencies_path %></li>
    <li><%= link_to 'Visualisation', chandelier_graphs_path %></li>
    </ul>
  </div>

  <div class="span8">
    <h4>Salary tools</h4>
      <p>No graph here yet. This will be likely a bar chart of any kind. This salary function has not been build in yet. This is merely to show that this function COULD be build in. Totally optional. If the salary is specified in the job description form (just the form to get in the database, not the actual job description) then it would be possible to have an overview of current salary expenses.</p>
      <p>It would be even more useful to have a base salary and an additional salary (competency pay, so an extra 10% e.g. if level intermediate). Then it would be possible to display the total 'costs' of the competency framework.</p>
      <h4>Track competency stage</h4>
      <p>At a certain stage it would be very useful to track levels as well. For example if 60% of the Dutch offices sits in level 'intermediate' while the german office has 80% in 'expert' it would be nice to track that. That would be very very valuable data because it displays the costs, and the level of growth inside an office (meaning in the german office in this example less competency growth is possible because highest stage is almost reached). If there is no growth possible anymore likely the competency reward system could lose its key function..</p>
  </div>

  <div class="span2">
    <%= render 'menu' %>
  </div>
</div>