config/routes.rb
Hrhome::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  match 'home/analytics' => 'home#analytics'
  match 'home/performance' => 'home#performance'
  match 'home/dictionary' => 'home#dictionary'
  match 'home/database' => 'home#database'

  resources :home

  match 'chandelier/graphs' => 'chandelier#graphs'
  match 'chandelier/fte' => 'chandelier#fte'
  match 'chandelier/employees' => 'chandelier#employees'
  match 'chandelier/salary' => 'chandelier#salary'

  resources :chandelier

  resources :competencies

  resources :positions do
    member do
      get 'edit_job_description'
      get 'edit_hr_profile'
      get 'edit_competency_profile'
      get 'steal'
    end
  end

  resources :offices

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    @tweets = Tweet.find(:all, :order => "created_at DESC")
    @positions = Position.all
    @prtalks = Position.find(:all, :order => "next_performance_talk ASC").last(7)
  end
  def performance

  end
  def analytics

  end

  def database
    @positions = Position.find(:all, :order => "created_at DESC")
    @tweets = Tweet.find(:all, :order => "created_at DESC")
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_all_positions_list.html.erb
<table class="table table-hover">
  <tr>
    <th>Job title</th>
    <th>Department</th>
    <th>Status</th>
    <th></th>
    <th></th>
  </tr>

<% @positions.each do |position| %>
    <tr>
      <td><%= link_to position.job_title, position %></td>
      <td><%= position.department %></td>
      <td><%= position.position_status %></td>
      <td><%= link_to 'Edit', edit_position_path(position) %></td>
      <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
<% end %>
</table>

app/views/home/_menu.html.erb
<link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />

<p><i>Office Toolbox</i></p>
<ul id="menu">
    <li><%= link_to 'Competency Dictionary', home_dictionary_path %></li>
    <li><%= link_to 'PRTs', home_performance_path %></li>
    <li><%= link_to 'Analytics', home_analytics_path %></li>
</ul>

app/views/home/_positions_list.html.erb
<%= link_to 'New Position', new_position_path %>

<table class="table table-hover">
  <tr>
    <th>Job title</th>
    <th>Department</th>
    <th>Status</th>
    <th></th>
    <th></th>
  </tr>

<% @positions.each do |position| %>
  <% if position.office == current_user.user_office %>
    <tr>
      <td><%= link_to position.job_title, position %></td>
      <td><%= position.department %></td>
      <td><%= position.position_status %></td>
      <td><%= link_to 'Edit', edit_position_path(position) %></td>
      <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
<% end %>
</table>

app/views/home/_prt_list.html.erb
<strong><em>Upcoming Performance Review Talks</em></strong>
<br/>
<br/>
<div class="prt">
    <table class="table">
      <tr>
        <th>Date</th>
        <th>Job title</th>
      </tr>

    <% @prtalks.each do |position| %>
      <% if position.office == current_user.user_office and position.next_performance_talk.present? %>
        <tr>
          <td><%= position.next_performance_talk.strftime("%d %B %Y") unless position.next_performance_talk.nil? %></td>
          <td><%= link_to position.job_title, position %></td>
        </tr>
      <% end %>
    <% end %>
    </table>
</div>

app/views/home/_requests.html.erb
<p>Here all the requests are submitted. For now this will be a competency dictionary request. So when I as a user would request a competency for the dictionary, I would be able to see the status of my request here. In the livescreen the request will appear and GPI would be able to change the status (from pending into accepted or rejected) which will be visible here then. Basically this screen is an interaction between the livescreen (GPI) and operational level.</p>

app/views/home/_tabs.html.erb
<ul id="myTab" class="nav nav-tabs">
  <li class="active"><a href="#activity" data-toggle="tab">Activity</a></li>
  <li><a href="#positions" data-toggle="tab">Positions</a></li>
  <li><a href="#requests" data-toggle="tab">Requests</a></li>
</ul>


<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade in active" id="activity">
    <% @tweets.each do |tweet| %>
      <% if tweet.tweet_office == current_user.user_office %>
        <p class="activity">The position <strong><%= tweet.tweet_position %></strong> <%= tweet.tweet_name %> at <%= tweet.created_at.strftime("%d %B %Y at %H:%M") %>.<br/>
        <% if tweet.body? %>
          (<%= tweet.body %>)
        <% end %>
        </p><br/>
      <% end %>
    <% end %>
  </div>

  <div class="tab-pane fade" id="positions">
    <p><%= render 'positions_list' %></p>
  </div>


  <div class="tab-pane fade" id="requests">
    <p><%= render 'requests' %></p>
  </div>
</div>

app/views/home/analytics.html.erb
<h4>Reporting</h4>
<%= link_to 'Back', home_index_path, :class => 'btn' %>

<div class="row-fluid">
  <div class="span1">
    <br/>
  </div>

  <div class="span4">
    <h4>HR data</h4>
    <p>In any decision making process it is essential to have the correct information. This function would provide the HR manager a neat overview of the current status of the HR in his/her NRO. For example diversity, average age, competency levels, number of vacancies, number of positions, number of unique positions, number of FTEs. In order to have this function the 'HR profile' is essential.</p>
  </div>

  <div class="span4">
    <h4>Salary analysis</h4>
    <p>If salary is defined in the database (in the job description form) it would be possible to run a salary analysis. Since this is on a national level it could be even more detailed. For example having an overview of who is in which competency category.</p>
    <p>Furtheremore it would be an unique opportunity for the HR manager to set a yearly salary expense budget. Then this page could display whether the are sitting above or under their yearly budget. This would be a nice little feature for budget control.</p>
  </div>

  <div class="span3">
    <br/>
  </div>
</div>

app/views/home/database.html.erb
<h2>All Job Descriptions</h2>
<br/>

<div class="row-fluid">
  <div class="span2">
    <center>
      <%= link_to 'Livescreen', chandelier_index_path, :class => 'btn btn-primary', :style => "color: white;" %>
    </center>

  </div>
  <div class="span8">
    <blockquote class="pull-right">
      <p>If money is your hope for independence you will never have it. The only real security that a man will have in this world is a reserve of knowledge, experience, and ability.</p>
      <small><cite title="Source Title">Henry Ford</cite></small>
    </blockquote>
  </div>
  <div class="span2">

  </div>
</div>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <%= render 'menu' %>
    </div>
    <div class="span8">
<ul id="myTab" class="nav nav-tabs">
  <li class="active"><a href="#activity" data-toggle="tab">Activity</a></li>
  <li><a href="#positions" data-toggle="tab">Positions</a></li>
  <li><a href="#requests" data-toggle="tab">Requests</a></li>
</ul>


    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade in active" id="activity">
          <% @tweets.each do |tweet| %>
              <p class="activity">The position <strong><%= tweet.tweet_position %></strong> <%= tweet.tweet_name %> at <%= tweet.created_at.strftime("%d %B %Y at %H:%M") %>.<br/>
              <% if tweet.body? %>
                (<%= tweet.body %>)
              <% end %>
              </p><br/>
          <% end %>
        </div>

        <div class="tab-pane fade" id="positions">
          <p><%= render 'all_positions_list' %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/dictionary.html.erb
<h4>Dictionary</h4>
<%= link_to 'Back', home_index_path, :class => 'btn' %>
<div class="row-fluid">
  <div class="span4">
    <h4>Requests</h4>
    <p>Requests can be filed here. So if you need an extra competency added to the dictionary it can be filed here and will appear on the livescreen which GPI manages. Also the status of the request will be displayed here (pending, approved, rejected).</p>
  </div>

  <div class="span4">
    <h4>Noticifactions</h4>
    <p>Notifications by GPI will be displayed also on this page. For example: "The latest version of the dictionary is out now, it contains two new competencies..". This aids GPI to commmunicate announcements to the operational levels</p>
    <h4>Language</h4>
    <p>The dictionary will be displayed in the language of choice of the user. So if French, then the French dictionary will be displayed.</p>
  </div>

  <div class="span4">
    <h4>Exporting to Excel</h4>
    <p>Another function which could be build in is the export function to excel. This could contain valuable data like, which position uses which competency. In this way it is easy to see any relation which aids the HR manager to make decisions. Also each level of profiency of the employee can be displayed in each competency which helps the HR manager to identify strenghts and weaknesses inside his/her organisation/staff.</p>
  </div>
</div>

app/views/home/index.html.erb
<h2>Greenpeace <%= office_name %></h2>
<br/>

<div class="row-fluid">
  <div class="span2">
    <center>
      <%= link_to 'Livescreen', chandelier_index_path, :class => 'btn btn-primary', :style => "color: white;" %>
    </center>

  </div>
  <div class="span8">
    <blockquote class="pull-right">
      <p>If money is your hope for independence you will never have it. The only real security that a man will have in this world is a reserve of knowledge, experience, and ability.</p>
      <small><cite title="Source Title">Henry Ford</cite></small>
    </blockquote>
  </div>
  <div class="span2">

  </div>
</div>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <%= render 'menu' %>
    </div>
    <div class="span8">
      <%= render "tabs" %>
    </div>
    <div class="span2">
      <%= render "prt_list" %>
    </div>
  </div>
</div>

app/views/home/performance.html.erb
<h4>Process control</h4>
<%= link_to 'Back', home_index_path, :class => 'btn' %>

<div class="row-fluid">
  <div class="span1">
    <br/>
  </div>

  <div class="span4">
    <h4>Set prt dates</h4>
    <p>It would be a neat function to control the prt process according competencies. This means that easily prt dates for each position can be filed into the database and can be displayed on the home screen. This will help the HR manager to have an overview of the PRT process.</p>
  </div>

  <div class="span4">
    <h4>Template handling</h4>
    <p>Of couse a function needs to be build in to generate a standard PRT template. This template just gets the data of the database like name, job title, date of birth and also a list of competencies and maybe even more. This could be very neat because then the HR manager could just generate a PRT form by pressing a button. Also this provides GPI the opportunity to provide several standard templates for PRTs.</p>
  </div>

  <div class="span3">
    <br/>
  </div>
</div>